// Generated by scripts/generate-companion-manifest.mjs from docs/evidence/companion-r2-v1.json.
// Do not edit by hand; run npm run prebuild after changing the evidence.
import type { CompanionSpecies, CompanionVariant } from "./companion";

export type CompanionAsset = Readonly<{
  assetId: string;
  species: CompanionSpecies;
  version: string;
  variant: CompanionVariant;
  url: string;
  bytes: number;
  sha256: string;
}>;

export const companionAssetManifest = {
  "bear": {
    "standard": {
      "assetId": "COMPANION-R2-002",
      "species": "bear",
      "version": "v007",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/bear/v007/standard.glb",
      "bytes": 1032708,
      "sha256": "48bfc97022f9799c2dccc58c0d0037a4cf06e846147e9b81864b814a5b214712"
    },
    "lite": {
      "assetId": "COMPANION-R2-001",
      "species": "bear",
      "version": "v007",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/bear/v007/lite.glb",
      "bytes": 518636,
      "sha256": "7960a83fc11ffb57943227172caebe0dbabbd78a84f302d69df50e8ddcbc4874"
    }
  },
  "rabbit": {
    "standard": {
      "assetId": "COMPANION-R2-004",
      "species": "rabbit",
      "version": "v002",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/rabbit/v002/standard.glb",
      "bytes": 1033524,
      "sha256": "25f0165c11eea89b9f90360e72435d4ccca98bf67d30b4d45df18f8b2c580704"
    },
    "lite": {
      "assetId": "COMPANION-R2-003",
      "species": "rabbit",
      "version": "v002",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/rabbit/v002/lite.glb",
      "bytes": 519456,
      "sha256": "b3559b2925bb16381adf954432e11541542c14bac7d6e6a52e7fa7f402825627"
    }
  },
  "cat": {
    "standard": {
      "assetId": "COMPANION-R2-006",
      "species": "cat",
      "version": "v002",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/cat/v002/standard.glb",
      "bytes": 1043208,
      "sha256": "5635a2e619e0d2bbeabe125423462350f7eae6ed8c1a6f0b6c4ca00ec1053afb"
    },
    "lite": {
      "assetId": "COMPANION-R2-005",
      "species": "cat",
      "version": "v002",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/cat/v002/lite.glb",
      "bytes": 528348,
      "sha256": "6a77bf8229d43f7094208143cb611bdbb46ffd185faf769efc5114d37e3ed960"
    }
  },
  "dog": {
    "standard": {
      "assetId": "COMPANION-R2-008",
      "species": "dog",
      "version": "v001",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/dog/v001/standard.glb",
      "bytes": 1032876,
      "sha256": "7c20c8aae1114e0be52da20acc11fc25fc60c9a4379af9fc8440b3ad9734cf8b"
    },
    "lite": {
      "assetId": "COMPANION-R2-007",
      "species": "dog",
      "version": "v001",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/dog/v001/lite.glb",
      "bytes": 518128,
      "sha256": "71762e0e00be1dd083fc0421533519921f0ac0c427fc08246632606406e92884"
    }
  },
  "red_panda": {
    "standard": {
      "assetId": "COMPANION-R2-010",
      "species": "red_panda",
      "version": "v003",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/red_panda/v003/standard.glb",
      "bytes": 1198468,
      "sha256": "29ddc43291cbfa3fc7c7479f983e5d560eddfa83a2966094773278f471f997a7"
    },
    "lite": {
      "assetId": "COMPANION-R2-009",
      "species": "red_panda",
      "version": "v003",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/red_panda/v003/lite.glb",
      "bytes": 644528,
      "sha256": "a6de102411b17295b2a9ea9a88592b4e4e9d4f3d8af73101f906f669ef927b48"
    }
  },
  "otter": {
    "standard": {
      "assetId": "COMPANION-R2-012",
      "species": "otter",
      "version": "v003",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/otter/v003/standard.glb",
      "bytes": 1068024,
      "sha256": "83106523fa0ab0e360c914d4522b3c5f4b32c0bdf0c29ee712565d1f5168330e"
    },
    "lite": {
      "assetId": "COMPANION-R2-011",
      "species": "otter",
      "version": "v003",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/otter/v003/lite.glb",
      "bytes": 548508,
      "sha256": "ac55dec25c28ff1cad1702f152987ed98e10620cc5f46a40862bfa6a86ffc27b"
    }
  },
  "capybara": {
    "standard": {
      "assetId": "COMPANION-R2-014",
      "species": "capybara",
      "version": "v002",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/capybara/v002/standard.glb",
      "bytes": 1027480,
      "sha256": "de7ceab11ef6d22682737b99dfa18f5930cae345fbbd965c4776b621101f8c9a"
    },
    "lite": {
      "assetId": "COMPANION-R2-013",
      "species": "capybara",
      "version": "v002",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/capybara/v002/lite.glb",
      "bytes": 513236,
      "sha256": "c6908aff87e737f53c7c1133bc509caa8ee5623521ffec5198f5c672bd003e20"
    }
  },
  "hedgehog": {
    "standard": {
      "assetId": "COMPANION-R2-016",
      "species": "hedgehog",
      "version": "v004",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/hedgehog/v004/standard.glb",
      "bytes": 1122852,
      "sha256": "a957fe8de2f6902198ebe4328589e2b852050a9656dda2504c5edfd89f7b0ede"
    },
    "lite": {
      "assetId": "COMPANION-R2-015",
      "species": "hedgehog",
      "version": "v004",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/hedgehog/v004/lite.glb",
      "bytes": 598996,
      "sha256": "7a8730bd05ef339dcdaa08af1d7e3741b54a1637d97f7c397901d107399e08fa"
    }
  },
  "penguin": {
    "standard": {
      "assetId": "COMPANION-R2-018",
      "species": "penguin",
      "version": "v002",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/penguin/v002/standard.glb",
      "bytes": 1104748,
      "sha256": "62159b3a39f921b0948bcc5862ff186578e55fe1e5dd9e9b6df803e6138e7144"
    },
    "lite": {
      "assetId": "COMPANION-R2-017",
      "species": "penguin",
      "version": "v002",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/penguin/v002/lite.glb",
      "bytes": 576468,
      "sha256": "d209bf3f3f1390679f3d4902b09705fba3f94e75156f59041c7c9392f9549fe5"
    }
  },
  "fox": {
    "standard": {
      "assetId": "COMPANION-R2-020",
      "species": "fox",
      "version": "v002",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/fox/v002/standard.glb",
      "bytes": 1081136,
      "sha256": "247dfd616e2be0955040961d74ef9942d63de06a5a711a04cd4f27377b4028aa"
    },
    "lite": {
      "assetId": "COMPANION-R2-019",
      "species": "fox",
      "version": "v002",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/fox/v002/lite.glb",
      "bytes": 556720,
      "sha256": "f4809971e572fe133465698ef73ac2b89ddff975141c8dc87a04f71f58637660"
    }
  },
  "squirrel": {
    "standard": {
      "assetId": "COMPANION-R2-022",
      "species": "squirrel",
      "version": "v001",
      "variant": "standard",
      "url": "https://sk7-companion.gkrry.com/companion/v1/squirrel/v001/standard.glb",
      "bytes": 1058696,
      "sha256": "1a256a93117cda2884a11ff91dc35eac33b5544595fc3e8d3d8882828cd5afff"
    },
    "lite": {
      "assetId": "COMPANION-R2-021",
      "species": "squirrel",
      "version": "v001",
      "variant": "lite",
      "url": "https://sk7-companion.gkrry.com/companion/v1/squirrel/v001/lite.glb",
      "bytes": 540440,
      "sha256": "3265086d5add45e0911852107b21db4a085349c002e743b2f403f8301426b6f5"
    }
  }
} as const satisfies Record<CompanionSpecies, Record<CompanionVariant, CompanionAsset>>;

export const companionManifestEvidence = {
  "deliveryVersion": "companion-r2-v1",
  "inventorySha256": "9fb23a63a612c7a30e8d01b6150bab258c239e4242d1f15224deeff5a1ecbd6f",
  "assetCount": 22,
  "totalBytes": 17867184,
  "customDomain": "https://sk7-assets.gomdory.com",
  "runtimeDeliveryDomain": "https://sk7-companion.gkrry.com"
} as const;

export function getCompanionAsset(species: CompanionSpecies, variant: CompanionVariant): CompanionAsset {
  return companionAssetManifest[species][variant];
}
