// Generated by scripts/verify-scene-manifest.mjs --write; do not edit.
export const sceneManifest = {
  "schemaVersion": 2,
  "manifestRevision": "s02-clay-001",
  "sourceCommit": "2c25a0d1cf41f8a5a2aa72f93b9dbe62cbe13d74",
  "assets": [
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [
        {
          "name": "celebrate",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        },
        {
          "name": "curious",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        },
        {
          "name": "greet",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        },
        {
          "name": "idle",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        },
        {
          "name": "move",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        },
        {
          "name": "rest",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        },
        {
          "name": "special",
          "durationSeconds": 4,
          "rootMotion": "unknown"
        }
      ],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "moa-bear-lite",
      "kind": "character",
      "revision": "v007",
      "status": "review",
      "provenance": {
        "sourceAssetId": "COMPANION-R2-001",
        "sourceHash": "7960a83fc11ffb57943227172caebe0dbabbd78a84f302d69df50e8ddcbc4874",
        "owner": "emotigom",
        "rightsBasis": "Issue #242 human use-scope decision",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/242"
      },
      "delivery": {
        "url": "https://sk7-companion.gkrry.com/companion/v1/bear/v007/lite.glb",
        "objectKey": "companion/v1/bear/v007/lite.glb",
        "sha256": "7960a83fc11ffb57943227172caebe0dbabbd78a84f302d69df50e8ddcbc4874",
        "byteLength": 518636,
        "mime": "model/gltf-binary"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-garden-gate-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-garden-gate-mobile320",
        "sourceHash": "b4f34a96987f9a80a33db9a08401b2d154b9f5445caa5e4b9c72ae05784bc689",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/garden-gate-mobile320-b4f34a96987f9a80.webp",
        "objectKey": "scene-review/s02/v1/garden-gate-mobile320-b4f34a96987f9a80.webp",
        "sha256": "b4f34a96987f9a80a33db9a08401b2d154b9f5445caa5e4b9c72ae05784bc689",
        "byteLength": 10266,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "procedural-landmarks",
      "kind": "environment",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "web/src/components/scene/environment.ts",
        "sourceHash": "03eca6fffba186488e5a39bcafedc751c4eff1d978feb3b92569d206d706ca7c",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored procedural review geometry",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "sourceModule": {
        "path": "web/src/components/scene/environment.ts",
        "sha256": "03eca6fffba186488e5a39bcafedc751c4eff1d978feb3b92569d206d706ca7c",
        "byteLength": 9223
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-herb-garden-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-herb-garden-mobile320",
        "sourceHash": "256383cacd9d477c168fc07add5d4c28e41865245bdada58276c693d1d018bc2",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/herb-garden-mobile320-256383cacd9d477c.webp",
        "objectKey": "scene-review/s02/v1/herb-garden-mobile320-256383cacd9d477c.webp",
        "sha256": "256383cacd9d477c168fc07add5d4c28e41865245bdada58276c693d1d018bc2",
        "byteLength": 9964,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-shade-tree-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-shade-tree-mobile320",
        "sourceHash": "e86bc25e9295c796cecbcfc9bca076f4a708e0539558d2672e1c898721873e81",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/shade-tree-mobile320-e86bc25e9295c796.webp",
        "objectKey": "scene-review/s02/v1/shade-tree-mobile320-e86bc25e9295c796.webp",
        "sha256": "e86bc25e9295c796cecbcfc9bca076f4a708e0539558d2672e1c898721873e81",
        "byteLength": 10354,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-footbridge-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-footbridge-mobile320",
        "sourceHash": "7be34a4a09e04d3f40d2639074607740a351e28ae1e7994811f486c54bce22dd",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/footbridge-mobile320-7be34a4a09e04d3f.webp",
        "objectKey": "scene-review/s02/v1/footbridge-mobile320-7be34a4a09e04d3f.webp",
        "sha256": "7be34a4a09e04d3f40d2639074607740a351e28ae1e7994811f486c54bce22dd",
        "byteLength": 10248,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-reading-shelter-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-reading-shelter-mobile320",
        "sourceHash": "c0929ce1ae2b881a70b6907fbc2458d4cb84372536d1a18564882bcda9082649",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/reading-shelter-mobile320-c0929ce1ae2b881a.webp",
        "objectKey": "scene-review/s02/v1/reading-shelter-mobile320-c0929ce1ae2b881a.webp",
        "sha256": "c0929ce1ae2b881a70b6907fbc2458d4cb84372536d1a18564882bcda9082649",
        "byteLength": 12118,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-pavilion-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-pavilion-mobile320",
        "sourceHash": "10344ad5b636e518a2f94a5ca363080a0714e1c4acdb6f1d9fabf73b59777169",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/pavilion-mobile320-10344ad5b636e518.webp",
        "objectKey": "scene-review/s02/v1/pavilion-mobile320-10344ad5b636e518.webp",
        "sha256": "10344ad5b636e518a2f94a5ca363080a0714e1c4acdb6f1d9fabf73b59777169",
        "byteLength": 12152,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-sunset-overlook-mobile320",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-sunset-overlook-mobile320",
        "sourceHash": "ddd405543b97490da383d9d0c2229809faabadd9e9d7425e4030e94c4205f5c8",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/sunset-overlook-mobile320-ddd405543b97490d.webp",
        "objectKey": "scene-review/s02/v1/sunset-overlook-mobile320-ddd405543b97490d.webp",
        "sha256": "ddd405543b97490da383d9d0c2229809faabadd9e9d7425e4030e94c4205f5c8",
        "byteLength": 10734,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-garden-gate-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-garden-gate-mobile390",
        "sourceHash": "160b4e9e10b1001bd0dd1751a6a23a0e03d0ef53d5239f535ed411e08b60a106",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/garden-gate-mobile390-160b4e9e10b1001b.webp",
        "objectKey": "scene-review/s02/v1/garden-gate-mobile390-160b4e9e10b1001b.webp",
        "sha256": "160b4e9e10b1001bd0dd1751a6a23a0e03d0ef53d5239f535ed411e08b60a106",
        "byteLength": 12780,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-herb-garden-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-herb-garden-mobile390",
        "sourceHash": "d5454f669dc2d52c7e863d47d22685aaf1b07e6197a3cd89461b3fb45f3c512f",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/herb-garden-mobile390-d5454f669dc2d52c.webp",
        "objectKey": "scene-review/s02/v1/herb-garden-mobile390-d5454f669dc2d52c.webp",
        "sha256": "d5454f669dc2d52c7e863d47d22685aaf1b07e6197a3cd89461b3fb45f3c512f",
        "byteLength": 12338,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-shade-tree-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-shade-tree-mobile390",
        "sourceHash": "abc09cf1e98ba4fe62a008efe83350512fc4583613e9855b344be0bef14f43be",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/shade-tree-mobile390-abc09cf1e98ba4fe.webp",
        "objectKey": "scene-review/s02/v1/shade-tree-mobile390-abc09cf1e98ba4fe.webp",
        "sha256": "abc09cf1e98ba4fe62a008efe83350512fc4583613e9855b344be0bef14f43be",
        "byteLength": 12776,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-footbridge-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-footbridge-mobile390",
        "sourceHash": "4cd6ccab4b5c0a0750a413f01c9daa7a9f4f923b6ed8307d3bf1762c061bada3",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/footbridge-mobile390-4cd6ccab4b5c0a07.webp",
        "objectKey": "scene-review/s02/v1/footbridge-mobile390-4cd6ccab4b5c0a07.webp",
        "sha256": "4cd6ccab4b5c0a0750a413f01c9daa7a9f4f923b6ed8307d3bf1762c061bada3",
        "byteLength": 12776,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-reading-shelter-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-reading-shelter-mobile390",
        "sourceHash": "d13f7eb6a5803418fc3027b04f857b5e60a98ff0cb3af4887a3e3c4defd5a9f6",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/reading-shelter-mobile390-d13f7eb6a5803418.webp",
        "objectKey": "scene-review/s02/v1/reading-shelter-mobile390-d13f7eb6a5803418.webp",
        "sha256": "d13f7eb6a5803418fc3027b04f857b5e60a98ff0cb3af4887a3e3c4defd5a9f6",
        "byteLength": 14912,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-pavilion-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-pavilion-mobile390",
        "sourceHash": "b83dd0c5e55c975903ab73a597e8e1961ef583ff680ea8bb78a76b47e08a5db5",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/pavilion-mobile390-b83dd0c5e55c9759.webp",
        "objectKey": "scene-review/s02/v1/pavilion-mobile390-b83dd0c5e55c9759.webp",
        "sha256": "b83dd0c5e55c975903ab73a597e8e1961ef583ff680ea8bb78a76b47e08a5db5",
        "byteLength": 14984,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-sunset-overlook-mobile390",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-sunset-overlook-mobile390",
        "sourceHash": "4b3f03c47ced09848db75fc735db09d13d13030ef0dddf1f4bd1b8593b0838b4",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/sunset-overlook-mobile390-4b3f03c47ced0984.webp",
        "objectKey": "scene-review/s02/v1/sunset-overlook-mobile390-4b3f03c47ced0984.webp",
        "sha256": "4b3f03c47ced09848db75fc735db09d13d13030ef0dddf1f4bd1b8593b0838b4",
        "byteLength": 13348,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-garden-gate-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-garden-gate-desktop",
        "sourceHash": "d43979ed01ef66af33165dfa9d811e4aadcf0a1d20ba02f00b41bcf3a419b440",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/garden-gate-desktop-d43979ed01ef66af.webp",
        "objectKey": "scene-review/s02/v1/garden-gate-desktop-d43979ed01ef66af.webp",
        "sha256": "d43979ed01ef66af33165dfa9d811e4aadcf0a1d20ba02f00b41bcf3a419b440",
        "byteLength": 23440,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-herb-garden-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-herb-garden-desktop",
        "sourceHash": "6943cc7c4e99ab30340f0bf493b0d28866a9f97a9b2b6c6b2bf94d88537eb8ee",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/herb-garden-desktop-6943cc7c4e99ab30.webp",
        "objectKey": "scene-review/s02/v1/herb-garden-desktop-6943cc7c4e99ab30.webp",
        "sha256": "6943cc7c4e99ab30340f0bf493b0d28866a9f97a9b2b6c6b2bf94d88537eb8ee",
        "byteLength": 22316,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-shade-tree-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-shade-tree-desktop",
        "sourceHash": "39bb4027700f629d9e1b7857a1ed53917d71fcc41f0fd8186e8a45a234959606",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/shade-tree-desktop-39bb4027700f629d.webp",
        "objectKey": "scene-review/s02/v1/shade-tree-desktop-39bb4027700f629d.webp",
        "sha256": "39bb4027700f629d9e1b7857a1ed53917d71fcc41f0fd8186e8a45a234959606",
        "byteLength": 23358,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-footbridge-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-footbridge-desktop",
        "sourceHash": "f163f48ff3ce5340d1ccdc86e8b44f2fd97f8994f723c141947b1b860c1abc05",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/footbridge-desktop-f163f48ff3ce5340.webp",
        "objectKey": "scene-review/s02/v1/footbridge-desktop-f163f48ff3ce5340.webp",
        "sha256": "f163f48ff3ce5340d1ccdc86e8b44f2fd97f8994f723c141947b1b860c1abc05",
        "byteLength": 23668,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-reading-shelter-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-reading-shelter-desktop",
        "sourceHash": "7a76a073a9a6f05cbde1a5564a560fda0d56dfa152cf6eabcb17556f7bbf2026",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/reading-shelter-desktop-7a76a073a9a6f05c.webp",
        "objectKey": "scene-review/s02/v1/reading-shelter-desktop-7a76a073a9a6f05c.webp",
        "sha256": "7a76a073a9a6f05cbde1a5564a560fda0d56dfa152cf6eabcb17556f7bbf2026",
        "byteLength": 27042,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-pavilion-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-pavilion-desktop",
        "sourceHash": "6a0f698a51b6d969b487d5f400eb092138623d2963fc3a0aa18ba64a10cdb6b4",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/pavilion-desktop-6a0f698a51b6d969.webp",
        "objectKey": "scene-review/s02/v1/pavilion-desktop-6a0f698a51b6d969.webp",
        "sha256": "6a0f698a51b6d969b487d5f400eb092138623d2963fc3a0aa18ba64a10cdb6b4",
        "byteLength": 27328,
        "mime": "image/webp"
      }
    },
    {
      "runtimeProfile": "three-0.185.1-webgl",
      "extensionsRequired": [],
      "decoderIds": [],
      "clips": [],
      "decorative": true,
      "containsText": false,
      "pointerPolicy": "inert",
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      },
      "id": "poster-sunset-overlook-desktop",
      "kind": "poster",
      "revision": "clay-001",
      "status": "review",
      "provenance": {
        "sourceAssetId": "render:poster-sunset-overlook-desktop",
        "sourceHash": "d7d0b9125c632c493f18ce30193b5d3d13a8398929a448f49e2f31f64c0672c9",
        "owner": "AI-HealthCare-05/AH_05_07",
        "rightsBasis": "Repository-authored scene render with registered bear-lite; character rights retained",
        "reviewReference": "https://github.com/AI-HealthCare-05/AH_05_07/issues/390"
      },
      "delivery": {
        "url": "/scene-review/s02/v1/sunset-overlook-desktop-d7d0b9125c632c49.webp",
        "objectKey": "scene-review/s02/v1/sunset-overlook-desktop-d7d0b9125c632c49.webp",
        "sha256": "d7d0b9125c632c493f18ce30193b5d3d13a8398929a448f49e2f31f64c0672c9",
        "byteLength": 24602,
        "mime": "image/webp"
      }
    }
  ],
  "recipes": [
    {
      "id": "s02-garden-gate-poster",
      "status": "review",
      "landmarkId": "garden-gate",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-garden-gate-mobile320",
        "poster-garden-gate-mobile390",
        "poster-garden-gate-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-garden-gate-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-garden-gate-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-garden-gate-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-garden-gate",
      "status": "review",
      "landmarkId": "garden-gate",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-garden-gate-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-herb-garden",
      "status": "review",
      "landmarkId": "herb-garden",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-herb-garden-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-shade-tree",
      "status": "review",
      "landmarkId": "shade-tree",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-shade-tree-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-footbridge",
      "status": "review",
      "landmarkId": "footbridge",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-footbridge-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-reading-shelter",
      "status": "review",
      "landmarkId": "reading-shelter",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-reading-shelter-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-pavilion",
      "status": "review",
      "landmarkId": "pavilion",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-pavilion-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-sunset-overlook",
      "status": "review",
      "landmarkId": "sunset-overlook",
      "screens": [
        "S02"
      ],
      "mode": "realtime",
      "assetIds": [
        "moa-bear-lite",
        "procedural-landmarks"
      ],
      "maxTier": 2,
      "motionPolicy": "neutral-static",
      "compositions": {
        "mobile320": {
          "projection": "orthographic",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "mobile390": {
          "projection": "orthographic",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.05,
            "position": [
              3.5,
              4,
              6
            ],
            "target": [
              0,
              0.77,
              0
            ],
            "characterAnchor": [
              -0.65,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.3,
              0,
              0
            ],
            "environmentScale": 0.8
          }
        },
        "desktop": {
          "projection": "orthographic",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": {
            "verticalSpan": 3.45,
            "position": [
              5,
              4,
              6
            ],
            "target": [
              0.25,
              0.77,
              0
            ],
            "characterAnchor": [
              -1.1,
              0.13,
              0.65
            ],
            "environmentAnchor": [
              0.65,
              0,
              0
            ],
            "environmentScale": 1
          }
        }
      },
      "fallback": {
        "tier1RecipeId": "s02-sunset-overlook-poster",
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-herb-garden-poster",
      "status": "review",
      "landmarkId": "herb-garden",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-herb-garden-mobile320",
        "poster-herb-garden-mobile390",
        "poster-herb-garden-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-herb-garden-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-herb-garden-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-herb-garden-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-shade-tree-poster",
      "status": "review",
      "landmarkId": "shade-tree",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-shade-tree-mobile320",
        "poster-shade-tree-mobile390",
        "poster-shade-tree-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-shade-tree-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-shade-tree-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-shade-tree-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-footbridge-poster",
      "status": "review",
      "landmarkId": "footbridge",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-footbridge-mobile320",
        "poster-footbridge-mobile390",
        "poster-footbridge-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-footbridge-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-footbridge-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-footbridge-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-reading-shelter-poster",
      "status": "review",
      "landmarkId": "reading-shelter",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-reading-shelter-mobile320",
        "poster-reading-shelter-mobile390",
        "poster-reading-shelter-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-reading-shelter-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-reading-shelter-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-reading-shelter-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-pavilion-poster",
      "status": "review",
      "landmarkId": "pavilion",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-pavilion-mobile320",
        "poster-pavilion-mobile390",
        "poster-pavilion-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-pavilion-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-pavilion-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-pavilion-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    },
    {
      "id": "s02-sunset-overlook-poster",
      "status": "review",
      "landmarkId": "sunset-overlook",
      "screens": [
        "S02"
      ],
      "mode": "static",
      "assetIds": [
        "poster-sunset-overlook-mobile320",
        "poster-sunset-overlook-mobile390",
        "poster-sunset-overlook-desktop"
      ],
      "maxTier": 1,
      "motionPolicy": "none",
      "compositions": {
        "mobile320": {
          "projection": "poster",
          "stageHeight": 200,
          "subjectMinHeight": 112,
          "subjectMaxHeight": 144,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-sunset-overlook-mobile320"
        },
        "mobile390": {
          "projection": "poster",
          "stageHeight": 240,
          "subjectMinHeight": 132,
          "subjectMaxHeight": 176,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-sunset-overlook-mobile390"
        },
        "desktop": {
          "projection": "poster",
          "stageHeight": 360,
          "subjectMinHeight": 200,
          "subjectMaxHeight": 280,
          "focalPoint": [
            0.35,
            0.55
          ],
          "secondaryCropping": false,
          "camera": null,
          "posterAssetId": "poster-sunset-overlook-desktop"
        }
      },
      "fallback": {
        "tier1RecipeId": null,
        "tier0": "css"
      },
      "measurement": {
        "status": "unmeasured",
        "encodedBytes": null,
        "drawCalls": null,
        "gpuBytes": null,
        "decodeMs": null,
        "environment": null
      }
    }
  ]
} as const;
